### ISSUE TITLE
SolveTheMergeQueue

### ISSUE THREAD

**Issue by RiesBen** [rinikerlab/reeds#21]
Let's solve the pile of changes

Merge Order:
1. [x] add potential_tresholds
2. [x] New Eoff Code #18 
3. [x] fixing small bug in sopt vis #19
4. [x] Energy offset input prep following ssm approach #20
